about/urls.py
from django.urls import path

from . import views

app_name = 'about'
urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path(
        '',
        views.index,
        name='index'
    ),
    path(
        'new/',
        views.new_post,
        name='new_post'
    ),
    path
    (
        'follow/',
        views.follow_index,
        name='follow_index'
    ),
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group'
    ),
    path(
        '<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        "<str:username>/follow/",
        views.profile_follow,
        name="profile_follow"
    ),
    path(
        "<str:username>/unfollow/",
        views.profile_unfollow,
        name="profile_unfollow"
    ),
    path(
        '<str:username>/<int:post_id>/',
        views.post_view,
        name='post'
    ),
    path(
        '<username>/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        '<str:username>/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path(
        '404/',
        views.page_not_found,
        name='404'
    ),
    path(
        '500/',
        views.server_error,
        name='500'
    ),
]

yatube/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import handler404, handler500
from django.conf.urls.static import static
from django.urls import include, path
from rest_framework.authtoken import views

handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa
'''
Импорт правил из приложений posts, admin, users
( Если правила в этом приложении не найдены, обращаемся к django.contrib...)
'''
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('api-token-auth/', views.obtain_auth_token),
]
if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import UniqueConstraint

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название группы',
                             null=False)
    slug = models.SlugField(verbose_name='Ссылка', unique=True,
                            help_text='Задайте ссылку на вашу группу')
    description = models.TextField(verbose_name='Описание группы',
                                   max_length=300)

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста')
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True,
                                    db_index=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               verbose_name='Автор поста',
                               related_name='posts')
    group = models.ForeignKey(Group, on_delete=models.SET_NULL,
                              verbose_name='Тег группы',
                              related_name='posts', blank=True, null=True,
                              help_text='Ключ для построения ссылки')
    image = models.ImageField(upload_to='posts/', verbose_name='Изображение', 
                              blank=True, null=True)

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             verbose_name='Ссылка на пост',
                             related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               verbose_name='Автор комментария',
                               related_name='comments')
    text = models.TextField(verbose_name='Текст комментария')
    created = models.DateTimeField('Дата комментария',
                                   auto_now_add=True,
                                   db_index=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.text


class Follow(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               verbose_name='Подписка',
                               related_name='following')
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             verbose_name='Подписчик',
                             related_name='follower')

    class Meta:
        UniqueConstraint(fields=['author', 'user'], name='follow_unique')

posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['group', 'text', 'image']


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.cache import cache_page

from yatube.settings import POSTS, CACHE_S
from .models import Group, Post, User, Follow
from .forms import PostForm, CommentForm


@cache_page(CACHE_S)
def index(request):
    post_list = Post.objects.all()
    paginator = Paginator(post_list, POSTS)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'paginator': paginator,
        'page': page,
    }
    return render(request, 'index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, POSTS)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'group': group,
        'paginator': paginator,
        'page': page,
    }
    return render(request, 'group.html', context)


@login_required
def new_post(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if not form.is_valid():
        return render(request, 'new.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:index')


def profile(request, username):
    author = get_object_or_404(User, username=username)
    posts = author.posts.all()
    paginator = Paginator(posts, POSTS)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user, author=author).exists()
    context = {
        'author': author,
        'paginator': paginator,
        'page': page,
        'following': following
    }
    return render(request, 'profile.html', context)


def post_view(request, username, post_id):
    author = get_object_or_404(User, username=username)
    post = get_object_or_404(Post, id=post_id, author=author)
    comments = post.comments.all()
    form = CommentForm()
    following = (
        request.user.is_authenticated
        and request.user != author
        and author.following.filter(user=request.user, author=author).exists()
    )
    context = {
        'author': author,
        'form': form,
        'post': post,
        'comments': comments,
        'following': following
    }
    return render(request, 'post.html', context)


@login_required
def add_comment(request, username, post_id):
    post = Post.objects.get(id=post_id, author__username=username)
    form = CommentForm(request.POST or None)
    comment = form.save(commit=False)
    comment.author = request.user
    comment.post = post
    comment.save()
    return redirect('posts:post', username, post_id)


@login_required
def post_edit(request, username, post_id):
    if not request.user.username == username:
        return redirect('posts:post', username, post_id)
    post = Post.objects.get(id=post_id, author=request.user)
    form = PostForm(request.POST or None, request.FILES or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post',
                        username=post.author.username, post_id=post.id)
    context = {
        'form': form,
        'post': post
    }
    return render(request, 'new.html', context)


def page_not_found(request, exception):
    return render(request, "misc/404.html", {"path": request.path}, status=404)


def server_error(request):
    return render(request, "misc/500.html", status=500)


@login_required
def follow_index(request):
    follow_posts = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(follow_posts, POSTS)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    context = {
        'paginator': paginator,
        'page': page,
    }
    return render(request, "follow.html", context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=author.username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=author.username)

templates/author.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
{% load user_filters %}
  <main role="main" class="container">
    <div class="row">
      <!-- Левый вспомогательный блок -->
      <div class="col-md-3 mb-3 mt-1">
        <div class="card">
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <div class="h3">
                  Данная страница всецело посвящена автору данного проекта(то есть мне)
                </div> 
              </li>
              <li class="list-group-item">
                <div class="h6 text-muted">
                  Через тернии к звездам...

                </div>
              </li>
            </ul>                                               
          </div>                    
        </div>                
      </div>
      <!-- Тело страницы -->
      <div class="col-md-9">
        <div class="card-body">                    
          <div class="card-text">
            <p>Сказали бы вы мне год назад, 
              что я буду сидеть вечерами и разбираться в документации Питона,
              осваивая его медленно, но верно. Я бы рассмеялся и сказал вам,
              что программирование - это вообще не мое, но вот он я.
              Пишу свой первый проект и радуюсь каждой маленькой победе над собой и над тренажером!
            </p>
          </div>                    
        </div>                
      </div>            
    </div>        
  </main>
{% endblock %}

templates/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
    <!-- Загрузка статики -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
</head>

<body>
    {% include 'nav.html' %}
    <main>
        <div class="container">
            {% block header %}
            <!--Переопределение наследников-->
            {% endblock %}

            {% block content %}
            <!-- Содержимое страницы -->
            {% endblock %}
        </div>
    </main>
    {% include 'footer.html' %}
</body>

</html>

templates/comments.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
<!-- Комментарии -->
<style>
    
    .media {
      overflow: hidden; 
      float: left;
    }
</style>
<div class="media card mb-4">
    <h5 class="card-header">Комментарии</h5>
{% for item in comments %}
<div class="media card mb-4">
    <div class="media-body card-body">
        <h5 class="mt-0">
            <a href="{% url 'posts:profile' item.author.username %}"
               name="comment_{{ item.id }}">
                {{ item.author.username }}
            </a>
        </h5>
        <p>{{ item.text | linebreaksbr }}</p>
    </div>
</div>
{% endfor %}
</div>

<div class="card my-4">
    <form method="post" action="{% url 'posts:add_comment' author.username post.id %}">
        {% csrf_token %}
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
            <div class="form-group">
                {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </div>
    </form>
</div>
{% endif %}

templates/follow.html
{% extends "base.html" %}
{% block title %}
  Последние обновления авторов
{% endblock %}

{% block content %}
{% include "menu.html" %}
  {% for post in page %}
  {% include "post_item.html" with post=post %}
  {% if not forloop.last %}
  <hr>
  {% endif %}
  {% endfor %}

  {% include "paginator.html" %}
  
{% endblock %} 

templates/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center ">
        <a href="{% url 'about:author' %}">Об авторе</a>
        <a href="{% url 'about:tech' %}">Технологии</a>
      </p>
    <p class="m-0 text-dark text-center ">Социальная сеть <span style="color:red">Ya</span>tube © {% now 'Y' %}, все права защищены.</p>
</footer> 

templates/group.html
{% extends "base.html" %}
{% block title %}
  Записи сообщества {{group.title}} 
{% endblock %}
{% block header %}
  {{group}}
{% endblock %}


{%block content%}
  <h1>{{ group.title }}</h1>
  <h1> 
    Записи сообщества {{group.title}}
  </h1>
 <p>
   {{group.description|linebreaksbr}}
 </p>
  {% for post in page %}
  {% include "post_item.html" with post=post %}
  {% endfor %}
  {% include "paginator.html" %}
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block title %}
  Последние обновления на сайте
{% endblock %}

{% block content %}
{% include "menu.html" %}
  {% for post in page %}
  {% include "post_item.html" with post=post %}
  {% if not forloop.last %}
  <hr>
  {% endif %}
  {% endfor %}

  {% include "paginator.html" %}
  
{% endblock %} 

templates/menu.html
{% if user.is_authenticated %} 
<div class="row">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if index %}active{% endif %}" href="{% url 'posts:index' %}">
                  Все авторы
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if follow %}active{% endif %}" href="/follow">
                Избранные авторы
            </a>
        </li>
    </ul>
</div>
{% endif %}

templates/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="{% url 'posts:index' %}"><span style="color:red">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        Пользователь: <a href = "{% url 'posts:profile' user.username %}" ><strong class="p-2 text-gray-dark">{{user.username}}</strong></a>
        <a class="p-2 text-dark" href="{% url 'posts:new_post' %}">Новая запись</a>
        <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
        <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav> 

templates/new.html
{% extends "base.html" %}
{% block title %}
{% if not post %}Добавить запись {% else %} Редактировать запись {% endif %}
{% endblock %}
{% block content %}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">{% if not post %} Добавить запись {% else %} Редактировать запись {% endif %}</div>
            <div class="card-body">

                {% for error in form.errors %}
                        <div class="alert alert-danger" role="alert">
                          {{ error|escape }}
                        </div>
                    {% endfor %}
                    <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                  
                   
                    {% for field in form %}
                    <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                            <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                            <div class="col-md-6">

                                {# подключаем фильтр и указываем класс #}
                                {{ field|addclass:"form-control" }}
                                
                                {% if field.help_text %}
                                <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                {% endif %}
                            </div>
                    </div>
                {% endfor %}
                <div class="col-md-6 offset-md-4">              
                    <button type="submit" class="btn btn-primary">
                        {% if post %} Сохранить {% else %} Добавить {% endif %}
                    </button>
                </div>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->
{% endblock %}

templates/paginator.html
{# Отрисовываем навигацию паджинатора только если есть и другие страницы #}
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

templates/post.html
{% extends "base.html" %}
{% block title %}
  Просмотр записи автора {{author.username}} 
{% endblock %}
{% block header %}
  {{author.username}}
{% endblock %}


{%block content%}
<main role="main" class="container">
    <div class="row">
            <div class="col-md-3 mb-3 mt-1">
                <div class="card">
                        <div class="card-body">
                                <div class="h2">
                                    <!-- Имя автора -->
                                    {{author.get_full_name}} 
                                </div>
                                <div class="h3 text-muted">
                                     <!-- username автора -->
                                     <a href = "{% url 'posts:profile' author.username %}" ><strong class="p-2 text-gray-dark">@{{author.username}}</strong></a>
                                </div>
                        </div>
                        <ul class="list-group list-group-flush">
                                <li class="list-group-item">
                                        <div class="h6 text-muted">
                                        Подписок: {{ author.follower.count }} <br />
                                        Подписан: {{ author.following.count }}
                                        </div>
                                </li>
                                <li class="list-group-item">
                                        <div class="h6 text-muted">
                                            <!--Во view нет вызова всех постов без ограничительного фильтра-->    
                                            Записей:{{author.posts.count}}
                                        </div>
                                </li>
                        </ul>
                </div>
        </div>

        <div class="col-md-9">

            <!-- Пост -->
            {% include "post_item.html" with post=post %}
            {% include "comments.html" with comments=comments %}
        </div>
     </div>
    </div>
</main>
{% endblock %}

templates/post_item.html
<div class="card mb-3 mt-1 shadow-sm">

    <!-- Отображение картинки -->
    {% load thumbnail %}
    {% thumbnail post.image "480x339" crop="center" upscale=True as im %}
    <img class="card-img" src="{{ im.url }}" />
    {% endthumbnail %}
    <!-- Отображение текста поста -->
    <div class="card-body">
      <p class="card-text">
        <!-- Ссылка на автора через @ -->
        <a name="post_{{ post.id }}" href="{% url 'posts:profile' post.author.username %}">
          <strong class="d-block text-gray-dark">@{{ post.author }}</strong>
        </a>
        {{ post.text|linebreaksbr }}
      </p>
  
      <!-- Если пост относится к какому-нибудь сообществу, то отобразим ссылку на него через # -->
      {% if post.group %}
      <a class="card-link muted" href="{% url 'posts:group' post.group.slug %}">
        <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
      </a>
      {% endif %}
  
      <!-- Отображение ссылки на комментарии -->
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          {% if post.comments.exists %}
          <div>
            Комментариев: {{ post.comments.count }}
          </div>
          {% endif %}
          <a class="btn btn-sm btn-primary" href="{% url 'posts:post' post.author.username post.id %}" role="button">
            Добавить комментарий
          </a>
          <!-- Ссылка на редактирование поста для автора -->
          {% if user == post.author %}
          <a class="btn btn-sm btn-info" href="{% url 'posts:post_edit' post.author.username post.id %}" role="button">
            Редактировать
          </a>
          {% endif %}
        </div>
  
        <!-- Дата публикации поста -->
        <small class="text-muted">{{ post.pub_date }}</small>
      </div>
    </div>
  </div> 

templates/tech.html
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
{% load user_filters %}
  <main role="main" class="container">
    <div class="row">
      <!-- Левый вспомогательный блок -->
      <div class="col-md-3 mb-3 mt-1">
        <div class="card">
          <div class="card-body">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                <div class="h3">
                  О Технологиях
                </div> 
              </li>
              <li class="list-group-item">
                <div class="h6 text-muted">
                  Полезный короткий текст о текхнологиях
                </div>
              </li>
            </ul>                                               
          </div>                    
        </div>                
      </div>
      <!-- Тело страницы -->
      <div class="col-md-9">
        <div class="card-body">                    
          <div class="card-text">
            <p>Технологии развиваются быстро, о них будет написано подробно чуть позже</p>
          </div>                    
        </div>                
      </div>            
    </div>        
  </main>
{% endblock %}